//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerminalLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root&gt;
        ///	&lt;CommandInfo&gt;
        ///		&lt;CommandCode&gt;0&lt;/CommandCode&gt;
        ///	&lt;/CommandInfo&gt;
        ///	&lt;CommandInfo&gt;
        ///		&lt;CommandCode&gt;1&lt;/CommandCode&gt;
        ///		&lt;CommandName&gt;Reset&lt;/CommandName&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///	&lt;/CommandInfo&gt;
        ///	&lt;CommandInfo&gt;
        ///		&lt;CommandCode&gt;2&lt;/CommandCode&gt;
        ///		&lt;CommandName&gt;Set Channel Inhibits&lt;/CommandName&gt;
        ///		&lt;Length&gt;3&lt;/Length&gt;
        ///	&lt;/CommandInfo&gt;
        ///	&lt;CommandInfo&gt;
        ///		&lt;CommandCode&gt;3&lt;/CommandCode&gt;
        ///		&lt;CommandName&gt;Display On&lt;/CommandName&gt;
        ///		&lt;Length&gt;1&lt;/Length&gt;
        ///	&lt;/Command [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root&gt;
        ///	&lt;GenericResponseInfo&gt;
        ///		&lt;GenericResponseCode&gt;0&lt;/GenericResponseCode&gt;
        ///	&lt;/GenericResponseInfo&gt;
        ///	&lt;GenericResponseInfo&gt;
        ///		&lt;GenericResponseCode&gt;1&lt;/GenericResponseCode&gt;
        ///	&lt;/GenericResponseInfo&gt;
        ///	&lt;GenericResponseInfo&gt;
        ///		&lt;GenericResponseCode&gt;2&lt;/GenericResponseCode&gt;
        ///	&lt;/GenericResponseInfo&gt;
        ///	&lt;GenericResponseInfo&gt;
        ///		&lt;GenericResponseCode&gt;3&lt;/GenericResponseCode&gt;
        ///	&lt;/GenericResponseInfo&gt;
        ///	&lt;GenericResponseInfo&gt;
        ///		&lt;GenericResponseCode&gt;4&lt;/GenericRe [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GenericResponses {
            get {
                return ResourceManager.GetString("GenericResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Root&gt;
        ///	&lt;PollResponseInfo&gt;
        ///		&lt;PollResponseCode&gt;0&lt;/PollResponseCode&gt;
        ///	&lt;/PollResponseInfo&gt;
        ///	&lt;PollResponseInfo&gt;
        ///		&lt;PollResponseCode&gt;1&lt;/PollResponseCode&gt;
        ///	&lt;/PollResponseInfo&gt;
        ///	&lt;PollResponseInfo&gt;
        ///		&lt;PollResponseCode&gt;2&lt;/PollResponseCode&gt;
        ///	&lt;/PollResponseInfo&gt;
        ///	&lt;PollResponseInfo&gt;
        ///		&lt;PollResponseCode&gt;3&lt;/PollResponseCode&gt;
        ///	&lt;/PollResponseInfo&gt;
        ///	&lt;PollResponseInfo&gt;
        ///		&lt;PollResponseCode&gt;4&lt;/PollResponseCode&gt;
        ///	&lt;/PollResponseInfo&gt;
        ///	&lt;PollResponseInfo&gt;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PollResponses {
            get {
                return ResourceManager.GetString("PollResponses", resourceCulture);
            }
        }
    }
}
